// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiyxvewddrkgsrsmgbvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpeXh2ZXdkZHJrZ3Nyc21nYnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDAxMDQsImV4cCI6MjA1MzY3NjEwNH0.Xo6HchzWvkP_gaVxyFFLtAeot_T4nUHynL8xbWxP_N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);